# Generated by Django 4.2.1 on 2023-06-01 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('discription', models.CharField(default='', max_length=500)),
                ('image', models.ImageField(blank='true', upload_to='images')),
                ('category', models.CharField(choices=[('newin', 'nw'), ('T-shirt', 'ts'), ('HOODIES', 'hoo'), ('SPORTSWEAR', 'sp'), ('shoes', 'sh'), ('bags', 'bg')], default='newin', max_length=10)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'M'), ('FEMALE', 'F'), ('BOTH', 'B')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('about', models.CharField(max_length=200)),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='jeanaapp.product')),
                ('size', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='jeanaapp.size')),
            ],
        ),
    ]
