# Generated by Django 4.2.1 on 2023-06-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeanaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ts', 't-shirt'), ('hoo', 'hoodies'), ('sp', 'sportswear'), ('sh', 'shoes'), ('bg', 'bags')], default='newin', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('B', 'Both')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank='true', upload_to='images/'),
        ),
    ]
