# Generated by Django 4.2.1 on 2023-06-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeanaapp', '0002_alter_product_category_alter_product_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='image',
            field=models.ImageField(blank='true', upload_to='images/'),
        ),
    ]
